### ISSUE TITLE
How to make date functions ?

### ISSUE THREAD

**Issue by erhanbicer** [ImangazalievM/ReActiveAndroid#11]
Ex.

```
CREATE TABLE `Example` (
	`id`	INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE,
	`timestamp`	**DATETIME DEFAULT CURRENT_TIMESTAMP**
);
```

How can I create a table like the one above?

**Comment by ImangazalievM** [comment]
SQLite does not have any support for date/time datatypes -- the dates should be
stored as milliseconds since the epoch:

```
The number of milliseconds since January 1, 1970, 00:00:00 GMT
```

ReActiveAndroid has predefined serializers for java.util,Date and java.sql.Date types, that convert data to Long, so you can define your custom serializer. For more information see [this](https://imangazalievm.gitbooks.io/reactiveandroid/content/type-converters.html) page.
